2012/03/28 16:37:01 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.username" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\helpers\CHtml.php(2044): CComponent->__get('username')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\helpers\CHtml.php(1774): CHtml::resolveValue(Object(LoginForm), 'username')
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\helpers\CHtml.php(1205): CHtml::activeInputField('text', Object(LoginForm), 'username', Array)
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\widgets\CActiveForm.php(575): CHtml::activeTextField(Object(LoginForm), 'username', Array)
#4 C:\xampp\htdocs\master\protected\views\site\login.php(25): CActiveForm->textField(Object(LoginForm), 'username')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\master\protected\controllers\SiteController.php(92): CController->render('login', Array)
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#17 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/user
---
2012/03/28 16:37:07 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.username" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\helpers\CHtml.php(2044): CComponent->__get('username')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\helpers\CHtml.php(1774): CHtml::resolveValue(Object(LoginForm), 'username')
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\helpers\CHtml.php(1205): CHtml::activeInputField('text', Object(LoginForm), 'username', Array)
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\widgets\CActiveForm.php(575): CHtml::activeTextField(Object(LoginForm), 'username', Array)
#4 C:\xampp\htdocs\master\protected\views\site\login.php(25): CActiveForm->textField(Object(LoginForm), 'username')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\master\protected\controllers\SiteController.php(92): CController->render('login', Array)
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#17 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/user
---
2012/03/28 16:57:46 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined. The SQL statement executed was: SELECT password FROM `users` `t` WHERE email = :email LIMIT 1. Bound with :uemail='mjstaffa@googlemail.com'.
in C:\xampp\htdocs\master\protected\components\UserIdentity.php (35)
in C:\xampp\htdocs\master\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (88)
2012/03/28 16:57:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined. The SQL statement executed was: SELECT password FROM `users` `t` WHERE email = :email LIMIT 1. Bound with :uemail='mjstaffa@googlemail.com'' in C:\xampp\htdocs\yii-1.1.10\framework\db\CDbCommand.php:528
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\db\CDbCommand.php(408): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(1287): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(1392): CActiveRecord->query(Object(CDbCriteria))
#3 C:\xampp\htdocs\master\protected\components\UserIdentity.php(35): CActiveRecord->find(Object(CDbCriteria))
#4 C:\xampp\htdocs\master\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii-1.1.10\framework\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): CModel->validate()
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/site/login
---
2012/03/28 16:58:06 [error] [exception.CException] exception 'CException' with message 'Property "User.passwd" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(144): CComponent->__get('passwd')
#1 C:\xampp\htdocs\master\protected\components\UserIdentity.php(42): CActiveRecord->__get('passwd')
#2 C:\xampp\htdocs\master\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii-1.1.10\framework\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/site/login
---
2012/03/28 16:58:18 [error] [exception.CException] exception 'CException' with message 'Property "User.uid" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(144): CComponent->__get('uid')
#1 C:\xampp\htdocs\master\protected\components\UserIdentity.php(52): CActiveRecord->__get('uid')
#2 C:\xampp\htdocs\master\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii-1.1.10\framework\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/site/login
---
2012/03/28 16:58:27 [error] [exception.CException] exception 'CException' with message 'Property "User.unickname" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(144): CComponent->__get('unickname')
#1 C:\xampp\htdocs\master\protected\components\UserIdentity.php(53): CActiveRecord->__get('unickname')
#2 C:\xampp\htdocs\master\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii-1.1.10\framework\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/site/login
---
2012/03/28 17:11:37 [error] [php] session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Cannot regenerate session id - headers already sent (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpSession.php:182)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CWebUser.php(228): CWebUser->changeIdentity()
#1 C:\xampp\htdocs\master\protected\models\LoginForm.php(84): CWebUser->login()
#2 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): LoginForm->login()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\models\LoginForm.php (84)
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (88)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 17:24:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(271): CController->missingAction('user')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('user')
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/user')
#3 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/master/index.php/site/user
---
2012/03/28 17:27:31 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\master\protected\controllers\SiteController.php:90) (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpRequest.php:716)
Stack trace:
#0 C:\xampp\htdocs\master\protected\controllers\SiteController.php(91): SiteController->redirect()
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (91)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 17:45:24 [error] [php] session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Cannot regenerate session id - headers already sent (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpSession.php:182)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CWebUser.php(228): CWebUser->changeIdentity()
#1 C:\xampp\htdocs\master\protected\models\LoginForm.php(85): CWebUser->login()
#2 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): LoginForm->login()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\models\LoginForm.php (85)
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (88)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 17:45:53 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\master\protected\models\LoginForm.php:85) (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpRequest.php:716)
Stack trace:
#0 C:\xampp\htdocs\master\protected\controllers\SiteController.php(90): SiteController->redirect()
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (90)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 17:55:04 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\master\protected\models\LoginForm.php:75) (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpRequest.php:716)
Stack trace:
#0 C:\xampp\htdocs\master\protected\controllers\SiteController.php(90): SiteController->redirect()
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (90)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 17:55:14 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\master\protected\models\LoginForm.php:75) (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpRequest.php:716)
Stack trace:
#0 C:\xampp\htdocs\master\protected\controllers\SiteController.php(90): SiteController->redirect()
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (90)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 18:00:47 [error] [exception.CException] exception 'CException' with message 'LoginForm and its behaviors do not have a method or closure named "login".' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:266
Stack trace:
#0 [internal function]: CComponent->__call('login', Array)
#1 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): LoginForm->login()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#8 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/site/login
---
2012/03/28 18:21:09 [error] [php] include(RWebUser.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii-1.1.10\framework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\YiiBase.php(198): import()
#1 C:\xampp\htdocs\yii-1.1.10\framework\base\CModule.php(387): createComponent()
#2 C:\xampp\htdocs\yii-1.1.10\framework\base\CModule.php(104): CWebApplication->getComponent()
#3 C:\xampp\htdocs\master\protected\models\LoginForm.php(84): CWebApplication->__get()
#4 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): LoginForm->login()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#11 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#12 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\models\LoginForm.php (84)
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (88)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 18:30:45 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\master\protected\models\LoginForm.php:85) (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpRequest.php:716)
Stack trace:
#0 C:\xampp\htdocs\master\protected\controllers\SiteController.php(90): SiteController->redirect()
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (90)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 18:32:42 [error] [exception.CException] exception 'CException' with message 'CWebUser.allowAutoLogin must be set true in order to use cookie-based authentication.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CWebUser.php:235
Stack trace:
#0 C:\xampp\htdocs\master\protected\models\LoginForm.php(84): CWebUser->login(Object(UserIdentity), 2592000)
#1 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): LoginForm->login()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#8 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/site/login
---
2012/03/28 18:34:56 [error] [exception.CException] exception 'CException' with message 'CWebUser.allowAutoLogin must be set true in order to use cookie-based authentication.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CWebUser.php:235
Stack trace:
#0 C:\xampp\htdocs\master\protected\models\LoginForm.php(84): CWebUser->login(Object(UserIdentity), 2592000)
#1 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): LoginForm->login()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#8 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/master/index.php/site/login
HTTP_REFERER=http://localhost/master/index.php/site/login
---
2012/03/28 18:35:24 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\yii-1.1.10\framework\utils\CVarDumper.php:43) (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpRequest.php:716)
Stack trace:
#0 C:\xampp\htdocs\master\protected\controllers\SiteController.php(90): SiteController->redirect()
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (90)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 18:37:44 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\yii-1.1.10\framework\utils\CVarDumper.php:43) (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpRequest.php:716)
Stack trace:
#0 C:\xampp\htdocs\master\protected\controllers\SiteController.php(90): SiteController->redirect()
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (90)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 18:37:56 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\yii-1.1.10\framework\utils\CVarDumper.php:43) (C:\xampp\htdocs\yii-1.1.10\framework\web\CHttpRequest.php:716)
Stack trace:
#0 C:\xampp\htdocs\master\protected\controllers\SiteController.php(90): SiteController->redirect()
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): SiteController->runAction()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): SiteController->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\master\index.php(13): CWebApplication->run()
REQUEST_URI=/master/index.php/site/login
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (90)
in C:\xampp\htdocs\master\index.php (13)
2012/03/28 18:40:13 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.states" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CWebUser.php(141): CComponent->__get('states')
#1 C:\xampp\htdocs\master\protected\views\layouts\main.php(46): CWebUser->__get('states')
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\widgets\CContentDecorator.php(77): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\widgets\CContentDecorator.php(55): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\widgets\COutputProcessor.php(45): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(207): COutputProcessor->run()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(301): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\master\protected\views\layouts\column1.php(5): CBaseController->endContent()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(785): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('')
#19 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('')
#20 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#21 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/master/index.php
HTTP_REFERER=http://localhost/master/index.php/site/login
---
2012/03/29 15:57:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(271): CController->missingAction('user')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('user')
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/user')
#3 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/master/index.php/site/user/
HTTP_REFERER=http://localhost/master/index.php/site/index
---
2012/03/29 16:03:05 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php:157
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/master/index.php/user/admin
HTTP_REFERER=http://localhost/master/index.php/user/
---
2012/03/29 16:09:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "users".' in C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(271): CController->missingAction('users')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('users')
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/users')
#3 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/master/index.php/site/users
HTTP_REFERER=http://localhost/master/index.php
---
2012/03/29 16:34:28 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'master.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\master\protected\modules\rights\components\RInstaller.php (180)
in C:\xampp\htdocs\master\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\master\index.php (13)
2012/03/29 16:34:33 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'master.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid. Bound with :userid='2'.
in C:\xampp\htdocs\master\protected\modules\rights\components\RAuthorizer.php (341)
in C:\xampp\htdocs\master\protected\modules\rights\components\RWebUser.php (21)
in C:\xampp\htdocs\master\protected\models\LoginForm.php (84)
2012/03/29 16:34:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'master.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid. Bound with :userid='2'' in C:\xampp\htdocs\yii-1.1.10\framework\db\CDbCommand.php:528
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\db\CDbCommand.php(390): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CDbAuthManager.php(334): CDbCommand->queryAll()
#2 C:\xampp\htdocs\master\protected\modules\rights\components\RAuthorizer.php(341): CDbAuthManager->getAuthAssignments('2')
#3 C:\xampp\htdocs\master\protected\modules\rights\components\RWebUser.php(21): RAuthorizer->isSuperuser('2')
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CWebUser.php(239): RWebUser->afterLogin(false)
#5 C:\xampp\htdocs\master\protected\models\LoginForm.php(84): CWebUser->login(Object(UserIdentity), 0)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(88): LoginForm->login()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('login')
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/master/site/login
HTTP_REFERER=http://localhost/master/site/login
---
2012/03/29 16:43:49 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'master.rights' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM Rights.
in C:\xampp\htdocs\master\protected\modules\rights\components\RInstaller.php (180)
in C:\xampp\htdocs\master\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\master\index.php (13)
2012/03/29 16:43:49 [error] [exception.CException] exception 'CException' with message 'Property "User.username" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(144): CComponent->__get('username')
#1 C:\xampp\htdocs\master\protected\modules\rights\components\behaviors\RUserBehavior.php(45): CActiveRecord->__get('username')
#2 C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php(112): RUserBehavior->getName()
#3 C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php(128): CComponent->__get('name')
#4 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(144): CComponent->__get('name')
#5 C:\xampp\htdocs\master\protected\modules\rights\components\RAuthorizer.php(300): CActiveRecord->__get('name')
#6 C:\xampp\htdocs\master\protected\modules\rights\controllers\InstallController.php(61): RAuthorizer->getSuperusers()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1145): InstallController->accessRules()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('ready')
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('rights/install/...')
#14 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/master/rights/install/ready
HTTP_REFERER=http://localhost/master/site/login
---
2012/03/29 16:46:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php:157
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('ready')
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('rights/install/...')
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/master/rights/install/ready
HTTP_REFERER=http://localhost/master/site/login
---
2012/03/29 16:46:58 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php:157
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('ready')
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('rights/install/...')
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/master/rights/install/ready
HTTP_REFERER=http://localhost/master/site/login
---
2012/03/29 16:49:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php:157
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('')
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('rights')
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/master/rights
---
2012/03/29 17:30:52 [error] [exception.CException] exception 'CException' with message 'Alias "ext.yii-facebook-opengraph.plugins.LikeButton" is invalid. Make sure it points to an existing PHP file.' in C:\xampp\htdocs\yii-1.1.10\framework\YiiBase.php:318
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(147): YiiBase::import('ext.yii-faceboo...', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/29 17:31:34 [error] [exception.CException] exception 'CException' with message 'Alias "ext.yii-facebook-opengraph.plugins.LikeButton" is invalid. Make sure it points to an existing PHP file.' in C:\xampp\htdocs\yii-1.1.10\framework\YiiBase.php:318
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(147): YiiBase::import('ext.yii-faceboo...', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/29 17:32:28 [error] [exception.CException] exception 'CException' with message 'Alias "ext.yii-facebook-opengraph.plugins.LikeButton" is invalid. Make sure it points to an existing PHP file.' in C:\xampp\htdocs\yii-1.1.10\framework\YiiBase.php:318
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(147): YiiBase::import('ext.yii-faceboo...', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/29 17:37:01 [error] [exception.CException] exception 'CException' with message 'Property "LikeButton.show-faces" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(162): CComponent->__set('show-faces', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/29 17:38:07 [error] [exception.CException] exception 'CException' with message 'Property "LikeButton.show-faces" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(162): CComponent->__set('show-faces', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/29 17:39:04 [error] [exception.CException] exception 'CException' with message 'Property "LikeButton.show-faces" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(162): CComponent->__set('show-faces', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/29 17:39:44 [error] [exception.CException] exception 'CException' with message 'Property "LikeButton.show-faces" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(162): CComponent->__set('show-faces', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/29 17:40:15 [error] [exception.CException] exception 'CException' with message 'Property "LikeButton.show-faces" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(162): CComponent->__set('show-faces', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/29 17:42:55 [error] [exception.CException] exception 'CException' with message 'Property "LikeButton.show-faces" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(162): CComponent->__set('show-faces', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/30 12:12:55 [error] [exception.CException] exception 'CException' with message 'Property "LoginButton.send" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWidgetFactory.php(162): CComponent->__set('send', true)
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'ext.yii-faceboo...', Array)
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(173): CBaseController->createWidget('ext.yii-faceboo...', Array)
#3 C:\xampp\htdocs\master\protected\views\site\index.php(14): CBaseController->widget('ext.yii-faceboo...', Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#8 C:\xampp\htdocs\master\protected\controllers\SiteController.php(32): CController->render('index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/rights/authItem/generate
---
2012/03/30 12:18:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('users')
#1 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/master/users
---
2012/03/30 12:23:04 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php:157
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('logout')
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/logout')
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/master/site/logout
HTTP_REFERER=http://localhost/master/site/index
---
2012/04/02 16:46:42 [error] [exception.Exception] exception 'Exception' with message 'Facebook needs the CURL PHP extension.' in C:\xampp\htdocs\master\protected\extensions\yii-facebook-opengraph\php-sdk-3.1.1\base_facebook.php:19
Stack trace:
#0 C:\xampp\htdocs\master\protected\extensions\yii-facebook-opengraph\SBaseFacebook.php(18): require_once()
#1 C:\xampp\htdocs\yii-1.1.10\framework\YiiBase.php(397): include('C:\xampp\htdocs...')
#2 [internal function]: YiiBase::autoload('SBaseFacebook')
#3 C:\xampp\htdocs\master\protected\extensions\yii-facebook-opengraph\SFacebook.php(474): spl_autoload_call('SBaseFacebook')
#4 C:\xampp\htdocs\master\protected\extensions\yii-facebook-opengraph\SFacebook.php(500): SFacebook->_getFacebook()
#5 C:\xampp\htdocs\master\protected\views\site\index.php(18): SFacebook->getUser()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#10 C:\xampp\htdocs\master\protected\controllers\SiteController.php(61): CController->render('index')
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#19 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('')
#21 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('')
#22 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#23 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/master/
---
2012/04/02 16:50:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php:157
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/master/site/register
---
2012/04/02 16:53:08 [warning] [application] Failed to set unsafe attribute "sendMe" of "RegisterForm".
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (115)
in C:\xampp\htdocs\master\index.php (13)
2012/04/02 16:53:08 [error] [exception.CException] exception 'CException' with message 'RegisterForm and its behaviors do not have a method or closure named "tableName".' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:266
Stack trace:
#0 [internal function]: CComponent->__call('tableName', Array)
#1 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(2262): RegisterForm->tableName()
#2 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(RegisterForm))
#3 C:\xampp\htdocs\yii-1.1.10\framework\validators\CUniqueValidator.php(87): CActiveRecord::model('RegisterForm')
#4 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CUniqueValidator->validateAttribute(Object(RegisterForm), 'useremail')
#5 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(RegisterForm), NULL)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(117): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionRegister()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#17 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#18 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#19 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/master/site/register
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 16:54:28 [error] [exception.CException] exception 'CException' with message 'RegisterForm and its behaviors do not have a method or closure named "tableName".' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:266
Stack trace:
#0 [internal function]: CComponent->__call('tableName', Array)
#1 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(2262): RegisterForm->tableName()
#2 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(RegisterForm))
#3 C:\xampp\htdocs\yii-1.1.10\framework\validators\CUniqueValidator.php(87): CActiveRecord::model('RegisterForm')
#4 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CUniqueValidator->validateAttribute(Object(RegisterForm), 'useremail')
#5 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(RegisterForm), NULL)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(117): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionRegister()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#17 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#18 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#19 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/master/site/register
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 16:55:00 [error] [exception.CException] exception 'CException' with message 'RegisterForm and its behaviors do not have a method or closure named "tableName".' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:266
Stack trace:
#0 [internal function]: CComponent->__call('tableName', Array)
#1 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(2262): RegisterForm->tableName()
#2 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(RegisterForm))
#3 C:\xampp\htdocs\yii-1.1.10\framework\validators\CUniqueValidator.php(87): CActiveRecord::model('RegisterForm')
#4 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CUniqueValidator->validateAttribute(Object(RegisterForm), 'useremail')
#5 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(RegisterForm), NULL)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(117): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionRegister()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#17 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#18 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#19 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/master/site/register
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 16:56:04 [error] [exception.CException] exception 'CException' with message 'RegisterForm and its behaviors do not have a method or closure named "tableName".' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:266
Stack trace:
#0 [internal function]: CComponent->__call('tableName', Array)
#1 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(2262): RegisterForm->tableName()
#2 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(RegisterForm))
#3 C:\xampp\htdocs\yii-1.1.10\framework\validators\CUniqueValidator.php(87): CActiveRecord::model('RegisterForm')
#4 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CUniqueValidator->validateAttribute(Object(RegisterForm), 'useremail')
#5 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(RegisterForm), NULL)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(117): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionRegister()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#17 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#18 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#19 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/master/site/register
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 16:57:55 [warning] [application] Failed to set unsafe attribute "sendMe" of "RegisterForm".
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (115)
in C:\xampp\htdocs\master\index.php (13)
2012/04/02 16:57:55 [error] [exception.CException] exception 'CException' with message 'RegisterForm and its behaviors do not have a method or closure named "tableName".' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:266
Stack trace:
#0 [internal function]: CComponent->__call('tableName', Array)
#1 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(2262): RegisterForm->tableName()
#2 C:\xampp\htdocs\yii-1.1.10\framework\db\ar\CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(RegisterForm))
#3 C:\xampp\htdocs\yii-1.1.10\framework\validators\CUniqueValidator.php(87): CActiveRecord::model('RegisterForm')
#4 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CUniqueValidator->validateAttribute(Object(RegisterForm), 'useremail')
#5 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(RegisterForm), NULL)
#6 C:\xampp\htdocs\master\protected\controllers\SiteController.php(117): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionRegister()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#15 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#17 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#18 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#19 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/master/site/register
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 17:00:07 [error] [exception.CException] exception 'CException' with message 'Table "users" does not have a column named "useremail".' in C:\xampp\htdocs\yii-1.1.10\framework\validators\CUniqueValidator.php:90
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CUniqueValidator->validateAttribute(Object(RegisterForm), 'useremail')
#1 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(RegisterForm), NULL)
#2 C:\xampp\htdocs\master\protected\controllers\SiteController.php(117): CModel->validate()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionRegister()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#14 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/master/site/register
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 17:01:40 [warning] [application] Failed to set unsafe attribute "useremail" of "RegisterForm".
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (115)
in C:\xampp\htdocs\master\index.php (13)
2012/04/02 17:01:40 [error] [exception.CException] exception 'CException' with message 'Property "RegisterForm.email" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\validators\CRequiredValidator.php(52): CComponent->__get('email')
#1 C:\xampp\htdocs\yii-1.1.10\framework\validators\CValidator.php(197): CRequiredValidator->validateAttribute(Object(RegisterForm), 'email')
#2 C:\xampp\htdocs\yii-1.1.10\framework\base\CModel.php(158): CValidator->validate(Object(RegisterForm), NULL)
#3 C:\xampp\htdocs\master\protected\controllers\SiteController.php(117): CModel->validate()
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionRegister()
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#14 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#15 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/master/site/register
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 17:01:52 [warning] [application] Failed to set unsafe attribute "useremail" of "RegisterForm".
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (115)
in C:\xampp\htdocs\master\index.php (13)
2012/04/02 17:01:57 [warning] [application] Failed to set unsafe attribute "useremail" of "RegisterForm".
in C:\xampp\htdocs\master\protected\controllers\SiteController.php (115)
in C:\xampp\htdocs\master\index.php (13)
2012/04/02 17:02:24 [error] [exception.CException] exception 'CException' with message 'Property "RegisterForm.rememberMe" is not defined.' in C:\xampp\htdocs\yii-1.1.10\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\master\protected\models\RegisterForm.php(87): CComponent->__get('rememberMe')
#1 C:\xampp\htdocs\master\protected\controllers\SiteController.php(117): RegisterForm->login()
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\actions\CInlineAction.php(50): SiteController->actionRegister()
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('register')
#12 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/register')
#13 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/master/site/register
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 17:04:02 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php:157
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('index')
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('site/index')
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/master/site/index
HTTP_REFERER=http://localhost/master/site/register
---
2012/04/02 17:04:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php:157
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.10\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.10\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.10\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(276): CController->run('')
#8 C:\xampp\htdocs\yii-1.1.10\framework\web\CWebApplication.php(135): CWebApplication->runController('')
#9 C:\xampp\htdocs\yii-1.1.10\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\master\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/master/
HTTP_REFERER=http://localhost/master/site/index
---
